---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: mynginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: mynginx2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: mynginx2
spec:
  ports:
  - nodePort: 32225
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
